#!/usr/bin/env python3
"""scripts/gen_llms_docs.py — generate AI-facing documentation.

Outputs (all committed to the repo):
  llms.txt                  — llms.txt index at repo root
  docs/llms/llms-full.md   — concatenated spec + getting-started + stdlib + error codes
  docs/llms/error-codes.md — auto-extracted error codes with handwritten notes overlay

Usage:
  python3 scripts/gen_llms_docs.py [--repo-root PATH]

Run this script after any of the following change:
  - docs/spec/en/language-spec.md
  - docs/getting-started/*.md
  - stdlib/**/*.ty
  - compiler/**/*.rs   (new error codes)
  - docs/llms/error-codes-notes.yaml
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
import warnings
from pathlib import Path

try:
    import yaml
except ModuleNotFoundError:
    sys.exit(
        "ERROR: PyYAML is required. Install it with: pip install pyyaml"
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def repo_root_from_git(script_path: Path) -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=script_path.parent,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError("Not inside a git repository.")
    return Path(result.stdout.strip())


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_if_changed(path: Path, content: str) -> bool:
    """Write content to path; return True if the file changed."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


# ---------------------------------------------------------------------------
# Error-code extraction
# ---------------------------------------------------------------------------

# Codes emitted via .with_code("Exxxx")
_WITH_CODE_RE = re.compile(r'with_code\("(E[0-9]+)"\)')
# Codes emitted as string literals: "error[Exxxx]:" (e.g. tyra-cli/main.rs)
_INLINE_CODE_RE = re.compile(r'"error\[(E[0-9]+)\]:')


def extract_error_codes(root: Path) -> list[str]:
    """Return sorted unique error codes found in compiler/ source.

    Two emission patterns are captured:
      - .with_code("Exxxx")  — standard diagnostic builder path
      - "error[Exxxx]:"      — CLI format-string path (e.g. tyra-cli/src/main.rs)
    """
    codes: set[str] = set()
    for rs_file in root.glob("compiler/**/*.rs"):
        text = rs_file.read_text(encoding="utf-8")
        for m in _WITH_CODE_RE.finditer(text):
            codes.add(m.group(1))
        for m in _INLINE_CODE_RE.finditer(text):
            codes.add(m.group(1))
    return sorted(codes)


def load_notes_overlay(notes_path: Path) -> dict[str, str]:
    with open(notes_path, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def render_error_codes_md(codes: list[str], notes: dict[str, str]) -> str:
    lines: list[str] = []
    lines.append("# Tyra error code reference")
    lines.append("")
    lines.append(
        "> Auto-generated by `scripts/gen_llms_docs.py`. "
        "Do not edit manually — edit `docs/llms/error-codes-notes.yaml` instead."
    )
    lines.append("")
    lines.append(f"Total codes: {len(codes)}")
    lines.append("")
    lines.append("| Code | Description |")
    lines.append("| ---- | ----------- |")

    missing: list[str] = []
    for code in codes:
        note = notes.get(code)
        if note is None:
            missing.append(code)
            note = "*(no description — add to error-codes-notes.yaml)*"
        lines.append(f"| `{code}` | {note} |")

    lines.append("")

    if missing:
        for code in missing:
            warnings.warn(
                f"gen_llms_docs: no overlay entry for {code} in "
                "docs/llms/error-codes-notes.yaml",
                stacklevel=2,
            )

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# llms-full.md builder
# ---------------------------------------------------------------------------

def render_llms_full(root: Path) -> str:
    parts: list[str] = []

    parts.append("# Tyra — full AI reference")
    parts.append("")
    parts.append(
        "> Auto-generated by `scripts/gen_llms_docs.py`. "
        "This file concatenates the language spec, getting-started guide, "
        "stdlib module list, and error codes for use by AI assistants."
    )
    parts.append("")

    # Language spec
    spec_path = root / "docs" / "spec" / "en" / "language-spec.md"
    parts.append("---")
    parts.append("")
    parts.append(read(spec_path))

    # Getting-started chapters (sorted)
    gs_dir = root / "docs" / "getting-started"
    chapters = sorted(gs_dir.glob("[0-9][0-9]-*.md"))
    if chapters:
        parts.append("")
        parts.append("---")
        parts.append("")
        parts.append("# Getting started")
        parts.append("")
        for ch in chapters:
            parts.append(read(ch))
            parts.append("")

    # Stdlib module list (dynamic — never hardcode count)
    stdlib_files = sorted(root.glob("stdlib/**/*.ty"))
    if stdlib_files:
        parts.append("---")
        parts.append("")
        parts.append("# Stdlib modules")
        parts.append("")
        parts.append(
            f"The following {len(stdlib_files)} stdlib module(s) ship with Tyra. "
            "Import them by name without a path prefix (e.g. `import io`)."
        )
        parts.append("")
        for ty_path in stdlib_files:
            rel = ty_path.relative_to(root / "stdlib")
            module_name = str(rel.with_suffix("")).replace("/", ".")
            parts.append(f"- `{module_name}` — `stdlib/{rel}`")
        parts.append("")

    # Error codes section (inline)
    error_codes_path = root / "docs" / "llms" / "error-codes.md"
    if error_codes_path.exists():
        parts.append("---")
        parts.append("")
        parts.append(read(error_codes_path))

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# llms.txt
# ---------------------------------------------------------------------------

def render_llms_txt(root: Path) -> str:
    # Determine version from CHANGELOG (first line starting with "## v")
    version = "unknown"
    changelog = root / "CHANGELOG.md"
    if changelog.exists():
        for line in changelog.read_text(encoding="utf-8").splitlines():
            # Match "## [0.9.0] ..." or "## [Unreleased] — v0.10.0"
            m = re.match(r"^##\s+\[([0-9][^\]]+)\]", line)
            if m:
                version = f"v{m.group(1)}"
                break
            m = re.match(r"^##\s+\[Unreleased\].*?(v[\d.]+)", line)
            if m:
                version = f"{m.group(1)}-dev"
                break

    lines: list[str] = []
    lines.append("# Tyra")
    lines.append("")
    lines.append(
        "Tyra is a statically typed, Ruby-inspired language that compiles to "
        "native binaries via LLVM. It targets readable, type-safe, "
        "easy-to-distribute practical programs."
    )
    lines.append("")
    lines.append(f"> Version: {version}")
    lines.append("")
    lines.append("## Links")
    lines.append("")
    lines.append(
        "- Language spec (English): "
        "https://github.com/tyra-lang/tyra/blob/main/docs/spec/en/language-spec.md"
    )
    lines.append(
        "- Getting started: "
        "https://github.com/tyra-lang/tyra/blob/main/docs/getting-started/README.md"
    )
    lines.append(
        "- Full AI reference (spec + guide + stdlib + errors): "
        "https://github.com/tyra-lang/tyra/blob/main/docs/llms/llms-full.md"
    )
    lines.append(
        "- Error code reference: "
        "https://github.com/tyra-lang/tyra/blob/main/docs/llms/error-codes.md"
    )
    lines.append(
        "- AI benchmark methodology: "
        "https://github.com/tyra-lang/tyra/blob/main/bench/ai-gen/METHODOLOGY.md"
    )
    lines.append("")
    lines.append("## Key facts for AI assistants")
    lines.append("")
    lines.append("- File extension: `.ty`")
    lines.append("- No `null` — use `Option<T>` and `Result<T,E>`")
    lines.append("- Blocks close with `end` (Ruby-style)")
    lines.append("- All imports at the top of the file")
    lines.append("- Formatter: `tyra fmt`; test runner: `tyra test`")
    lines.append("- Abilities (type classes): `Eq`, `Hash`, `Ord`, `Debug`")
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate AI-facing documentation for Tyra."
    )
    ap.add_argument(
        "--repo-root",
        default=None,
        help="Path to repo root (auto-detected from git if omitted).",
    )
    args = ap.parse_args()

    script_path = Path(__file__).resolve()
    root = Path(args.repo_root) if args.repo_root else repo_root_from_git(script_path)

    notes_path = root / "docs" / "llms" / "error-codes-notes.yaml"
    if not notes_path.exists():
        sys.exit(f"ERROR: overlay not found: {notes_path}")

    # 1. Extract error codes and render error-codes.md
    codes = extract_error_codes(root)
    notes = load_notes_overlay(notes_path)
    error_codes_md = render_error_codes_md(codes, notes)
    ec_path = root / "docs" / "llms" / "error-codes.md"
    changed_ec = write_if_changed(ec_path, error_codes_md)
    print(f"{'updated' if changed_ec else 'unchanged'}: {ec_path.relative_to(root)}")

    # 2. Render llms-full.md (depends on error-codes.md being written first)
    llms_full_md = render_llms_full(root)
    lf_path = root / "docs" / "llms" / "llms-full.md"
    changed_lf = write_if_changed(lf_path, llms_full_md)
    print(f"{'updated' if changed_lf else 'unchanged'}: {lf_path.relative_to(root)}")

    # 3. Render llms.txt at repo root
    llms_txt = render_llms_txt(root)
    lt_path = root / "llms.txt"
    changed_lt = write_if_changed(lt_path, llms_txt)
    print(f"{'updated' if changed_lt else 'unchanged'}: {lt_path.relative_to(root)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
