use serde::{Deserialize, Serialize};
use std::path::Path;

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------

/// Content of `Tyra.lock`.
///
/// Records every resolved dependency (direct and transitive) with its exact
/// `rev` so builds are reproducible across machines and CI pipelines.
/// Floating constraints (e.g. `branch = "main"`) are resolved to an exact
/// SHA before writing; `--locked` mode reads the lock and skips re-resolution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lockfile {
    pub version: u32,
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
}

/// A single entry in `Tyra.lock`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedPackage {
    /// Dependency key from `[dependencies]`.
    pub name: String,
    /// Canonical source URI:
    /// - `"git+<url>"` for git dependencies
    /// - `"path+<relative-path>"` for path dependencies
    pub source: String,
    /// Exact resolved commit SHA (git deps only; absent for path deps).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rev: Option<String>,
    /// Floating branch constraint that was resolved to `rev`.
    /// Absent for pinned-rev deps and path deps.
    /// Stored so that `--locked` can detect if the branch name changes and
    /// require a fresh `tyra mod sync`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    /// `[package].version` from the fetched `Tyra.toml` (informational).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pkg_version: Option<String>,
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum LockfileError {
    Io(std::io::Error),
    Parse(String),
    VersionMismatch(u32),
}

impl std::fmt::Display for LockfileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LockfileError::Io(e) => write!(f, "I/O error: {e}"),
            LockfileError::Parse(e) => write!(f, "Tyra.lock parse error: {e}"),
            LockfileError::VersionMismatch(v) => write!(
                f,
                "Tyra.lock version {v} is not supported by this toolchain (expected 1)"
            ),
        }
    }
}

impl std::error::Error for LockfileError {}

impl From<std::io::Error> for LockfileError {
    fn from(e: std::io::Error) -> Self {
        LockfileError::Io(e)
    }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

const LOCK_VERSION: u32 = 1;

/// Read `Tyra.lock` from `project_root`.
/// Returns `Ok(None)` when the file does not exist yet.
pub fn load_lockfile(project_root: &Path) -> Result<Option<Lockfile>, LockfileError> {
    let path = project_root.join("Tyra.lock");
    if !path.is_file() {
        return Ok(None);
    }
    let text = std::fs::read_to_string(&path)?;
    let lf: Lockfile = toml::from_str(&text).map_err(|e| LockfileError::Parse(e.to_string()))?;
    if lf.version != LOCK_VERSION {
        return Err(LockfileError::VersionMismatch(lf.version));
    }
    Ok(Some(lf))
}

/// Atomically write `Tyra.lock` to `project_root`.
pub fn write_lockfile(project_root: &Path, lf: &Lockfile) -> Result<(), std::io::Error> {
    let path = project_root.join("Tyra.lock");
    let tmp = project_root.join(".Tyra.lock.tmp");
    let header = "# Generated by `tyra mod sync`. Commit this file to version control.\n# Do not edit manually.\n";
    let body = toml::to_string_pretty(lf).expect("lockfile serialization is infallible");
    std::fs::write(&tmp, format!("{header}{body}"))?;
    std::fs::rename(&tmp, &path)?;
    Ok(())
}

/// Build a `Lockfile` from a list of resolved packages, sort by name, and write.
pub fn build_and_write(
    project_root: &Path,
    mut packages: Vec<LockedPackage>,
) -> Result<Lockfile, std::io::Error> {
    packages.sort_by(|a, b| a.name.cmp(&b.name));
    let lf = Lockfile {
        version: LOCK_VERSION,
        packages,
    };
    write_lockfile(project_root, &lf)?;
    Ok(lf)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip_empty() {
        let lf = Lockfile {
            version: 1,
            packages: vec![],
        };
        let s = toml::to_string_pretty(&lf).unwrap();
        let lf2: Lockfile = toml::from_str(&s).unwrap();
        assert_eq!(lf2.version, 1);
        assert!(lf2.packages.is_empty());
    }

    #[test]
    fn roundtrip_git_entry() {
        let lf = Lockfile {
            version: 1,
            packages: vec![LockedPackage {
                name: "foo".to_string(),
                source: "git+https://github.com/user/foo.git".to_string(),
                rev: Some("abc1234".to_string()),
                branch: None,
                pkg_version: Some("1.0.0".to_string()),
            }],
        };
        let s = toml::to_string_pretty(&lf).unwrap();
        let lf2: Lockfile = toml::from_str(&s).unwrap();
        assert_eq!(lf2.packages[0].rev.as_deref(), Some("abc1234"));
        assert_eq!(lf2.packages[0].pkg_version.as_deref(), Some("1.0.0"));
    }

    #[test]
    fn roundtrip_path_entry() {
        let lf = Lockfile {
            version: 1,
            packages: vec![LockedPackage {
                name: "bar".to_string(),
                source: "path+../bar".to_string(),
                rev: None,
                branch: None,
                pkg_version: None,
            }],
        };
        let s = toml::to_string_pretty(&lf).unwrap();
        assert!(!s.contains("rev ="));
        assert!(!s.contains("branch ="));
        assert!(!s.contains("pkg_version ="));
    }

    #[test]
    fn roundtrip_branch_entry() {
        let lf = Lockfile {
            version: 1,
            packages: vec![LockedPackage {
                name: "baz".to_string(),
                source: "git+https://github.com/user/baz.git".to_string(),
                rev: Some("deadbeef".to_string()),
                branch: Some("main".to_string()),
                pkg_version: None,
            }],
        };
        let s = toml::to_string_pretty(&lf).unwrap();
        assert!(s.contains("branch = \"main\""));
        let lf2: Lockfile = toml::from_str(&s).unwrap();
        assert_eq!(lf2.packages[0].branch.as_deref(), Some("main"));
        assert_eq!(lf2.packages[0].rev.as_deref(), Some("deadbeef"));
    }
}
